// @generated by protobuf-ts 2.9.4 with parameter output_javascript
// @generated from protobuf file "pbf/wallet/api.proto" (package "wallet", syntax proto3)
// tslint:disable
/**
 * @generated ServiceType for protobuf service wallet.API
 */
export declare const API: any;
