// @generated by protobuf-ts 2.9.4 with parameter output_javascript
// @generated from protobuf file "pbf/note/api.proto" (package "note", syntax proto3)
// tslint:disable
/**
 * @generated ServiceType for protobuf service note.API
 */
export declare const API: any;
